const quizzes = [
  {
    answers: ['카를 마르크스', 'Karl Marx'],
    category: 'general',
    difficulty: 'hard',
    question: '‘자본론’을 저술하며 공산주의 사상의 기반을 만든 인물은?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['노벨', 'Alfred Nobel'],
    category: 'general',
    difficulty: 'hard',
    question: '다이너마이트를 발명하고 국제적인 상을 제정한 인물은?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['사하라 사막', 'Sahara Desert'],
    category: 'general',
    difficulty: 'hard',
    question: '세계에서 가장 큰 뜨거운 사막은 어디인가요?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['루이스 파스퇴르', 'Louis Pasteur'],
    category: 'general',
    difficulty: 'hard',
    question: '백신과 저온살균법으로 유명한 프랑스의 생물학자는 누구인가요?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['피타고라스 정리', 'Pythagorean theorem'],
    category: 'general',
    difficulty: 'hard',
    question:
      '직각삼각형에서 빗변의 제곱은 두 변의 제곱의 합과 같다는 수학 법칙은?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['아틀란티스', 'Atlantis'],
    category: 'general',
    difficulty: 'hard',
    question: '플라톤이 언급한 신화 속의 잃어버린 대륙은 무엇인가요?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['카멜레온', 'Chameleon'],
    category: 'general',
    difficulty: 'hard',
    question: '자신의 피부색을 환경에 따라 바꾸는 파충류는?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['엔트로피', 'Entropy'],
    category: 'general',
    difficulty: 'hard',
    question: '열역학 제2법칙과 관련된 무질서도의 개념은?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['고대 로마', 'Ancient Rome'],
    category: 'general',
    difficulty: 'hard',
    question: '콜로세움과 글래디에이터로 유명한 고대 문명은?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['그린피스', 'Greenpeace'],
    category: 'general',
    difficulty: 'hard',
    question: '환경 보호와 평화 운동을 위해 활동하는 국제 NGO는?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['퀴리 부인', 'Marie Curie'],
    category: 'general',
    difficulty: 'hard',
    question: '방사능 연구로 노벨상을 두 번 수상한 과학자는 누구인가요?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['아르마딜로', 'Armadillo'],
    category: 'general',
    difficulty: 'hard',
    question: '등껍질로 몸을 보호하는 포유류는 무엇인가요?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['루소', 'Rousseau'],
    category: 'general',
    difficulty: 'hard',
    question: '‘사회계약론’을 저술한 프랑스 계몽사상가는 누구인가요?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['스티븐 호킹', 'Stephen Hawking'],
    category: 'general',
    difficulty: 'hard',
    question: '‘시간의 역사’로 유명한 이론 물리학자는 누구인가요?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['미토콘드리아', 'Mitochondria'],
    category: 'general',
    difficulty: 'hard',
    question: "세포의 에너지원으로 '세포의 발전소'라 불리는 기관은?",
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['포노사피엔스', 'Phono Sapiens'],
    category: 'general',
    difficulty: 'hard',
    question: '스마트폰을 중심으로 생활하는 신인류를 부르는 용어는?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['보로노이 다이어그램', 'Voronoi diagram'],
    category: 'general',
    difficulty: 'hard',
    question: '공간을 가장 가까운 점 기준으로 분할하는 수학적 개념은?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['프레온 가스', 'Freon'],
    category: 'general',
    difficulty: 'hard',
    question: '오존층 파괴의 주요 원인 중 하나인 냉매 성분은?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['호모 에렉투스', 'Homo erectus'],
    category: 'general',
    difficulty: 'hard',
    question: '직립보행을 한 초기 인류 종은 무엇인가요?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['테슬라 코일', 'Tesla coil'],
    category: 'general',
    difficulty: 'hard',
    question: '고전압 고주파 전류를 발생시키는 장치는?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['로제타 스톤', 'Rosetta Stone'],
    category: 'general',
    difficulty: 'hard',
    question: '이집트 상형문자를 해독할 수 있게 해준 고대 석판의 이름은?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['마그나 카르타', 'Magna Carta'],
    category: 'general',
    difficulty: 'hard',
    question: '1215년에 영국 왕의 권한을 제한한 역사적 문서는?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['칼 세이건', 'Carl Sagan'],
    category: 'general',
    difficulty: 'hard',
    question: '‘코스모스’라는 대중 과학서를 집필한 천문학자는?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['초끈 이론', 'String theory'],
    category: 'general',
    difficulty: 'hard',
    question: '모든 물리 법칙을 하나로 설명하려는 이론 중 하나는?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['파리 조약', 'Treaty of Paris'],
    category: 'general',
    difficulty: 'hard',
    question: '1783년에 미국 독립 전쟁을 공식 종결시킨 조약은?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['상대성이론', 'Theory of Relativity'],
    category: 'general',
    difficulty: 'hard',
    question: '시공간과 중력의 관계를 설명하는 아인슈타인의 이론은?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['진화론', 'Theory of Evolution'],
    category: 'general',
    difficulty: 'hard',
    question: '찰스 다윈이 제안한 생물의 변화를 설명하는 이론은?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['아즈텍 문명', 'Aztec civilization'],
    category: 'general',
    difficulty: 'hard',
    question: '멕시코 중앙 고원에서 번성한 고대 문명은?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['한자', 'Chinese characters'],
    category: 'general',
    difficulty: 'hard',
    question: '한국, 중국, 일본에서 사용된 고대 문자 체계는?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['헤겔', 'Hegel'],
    category: 'general',
    difficulty: 'hard',
    question: '변증법적 사유로 유명한 독일 철학자는 누구인가요?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['스푸트니크', 'Sputnik'],
    category: 'general',
    difficulty: 'hard',
    question: '세계 최초의 인공위성 이름은 무엇인가요?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['베르사유 조약', 'Treaty of Versailles'],
    category: 'general',
    difficulty: 'hard',
    question: '제1차 세계대전을 공식적으로 종결시킨 조약은?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['오로라', 'Aurora'],
    category: 'general',
    difficulty: 'hard',
    question: '지구 극지방에서 볼 수 있는 아름다운 빛 현상은 무엇인가요?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['DNA', '디엔에이', 'Deoxyribonucleic acid'],
    category: 'general',
    difficulty: 'hard',
    question: '유전 정보를 담고 있는 이중 나선 구조의 분자는 무엇인가요?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['코페르니쿠스', 'Copernicus'],
    category: 'general',
    difficulty: 'hard',
    question: '지동설을 주장한 폴란드 천문학자는 누구인가요?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['플랑크 상수', "Planck's constant"],
    category: 'general',
    difficulty: 'hard',
    question: '양자역학에서 에너지와 진동수의 비례 상수는 무엇인가요?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['세포막', 'Cell membrane'],
    category: 'general',
    difficulty: 'hard',
    question: '세포의 내부와 외부를 구분하고 물질 출입을 조절하는 구조는?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['알렉산더 대왕', 'Alexander the Great'],
    category: 'general',
    difficulty: 'hard',
    question: '마케도니아 제국을 이끌며 광범위한 정복을 이룬 인물은?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['산스크리트어', 'Sanskrit'],
    category: 'general',
    difficulty: 'hard',
    question: '힌두교의 경전이 쓰인 고대 인도 언어는 무엇인가요?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['파보 누르미', 'Paavo Nurmi'],
    category: 'general',
    difficulty: 'hard',
    question:
      '‘날으는 핀란드인’으로 불리며 올림픽에서 9개의 금메달을 딴 육상 선수는 누구인가요?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['아르키메데스', 'Archimedes'],
    category: 'general',
    difficulty: 'hard',
    question: "'유레카'로 유명한 고대 그리스 수학자이자 과학자는 누구인가요?",
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['해왕성', 'Neptune'],
    category: 'general',
    difficulty: 'hard',
    question: '태양계에서 태양으로부터 가장 멀리 떨어진 행성은?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['쿼크', 'Quark'],
    category: 'general',
    difficulty: 'hard',
    question: '양성자와 중성자를 구성하는 기본 입자는 무엇인가요?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['하이젠베르크', 'Heisenberg'],
    category: 'general',
    difficulty: 'hard',
    question: '불확정성 원리를 제시한 독일의 물리학자는 누구인가요?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['에디슨', 'Edison'],
    category: 'general',
    difficulty: 'hard',
    question: '전구 발명으로 널리 알려진 미국의 발명가는 누구인가요?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['라틴어', 'Latin'],
    category: 'general',
    difficulty: 'hard',
    question:
      '과거 로마 제국에서 사용되었으며 오늘날 의학과 법률 용어에 많이 쓰이는 언어는?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['킬리만자로', 'Kilimanjaro'],
    category: 'general',
    difficulty: 'hard',
    question: '아프리카 대륙에서 가장 높은 산은 무엇인가요?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['몽골', 'Mongolia'],
    category: 'general',
    difficulty: 'hard',
    question: '칭기즈 칸의 고향이자 유목 문화로 유명한 나라는?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['노스트라다무스', 'Nostradamus'],
    category: 'general',
    difficulty: 'hard',
    question: '예언서로 유명한 16세기 프랑스의 점성술사는 누구인가요?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
  {
    answers: ['양자역학', 'Quantum Mechanics'],
    category: 'general',
    difficulty: 'hard',
    question: '입자의 불확정성과 파동-입자 이중성을 설명하는 물리학 분야는?',
    questionFormat: 'short',
    quizType: 'knowledge',
  },
];

export const uploadQuiz = async (insertQuiz: any) => {
  for (const quiz of quizzes) {
    try {
      await insertQuiz(quiz as any);
      console.log(`✅ Uploaded: ${quiz.question}`);
    } catch (error) {
      console.error(`❌ Failed: ${quiz.question}`, error);
    }
  }
};
