const quizzes = [
  {
    answer: '노이즈 음악',
    category: 'kpop-music',
    difficulty: 'hard',
    options: ['노이즈 음악', '조성 음악', '현대 클래식', '월드 뮤직'],
    question:
      '기존 음악의 음고, 리듬을 벗어나 소음과 같은 음향을 예술로 수용한 음악은?',
    questionFormat: 'multiple',
    quizType: 'knowledge',
  },
  {
    answer: '미디',
    category: 'kpop-music',
    difficulty: 'hard',
    options: ['미디', 'AI 작곡', '디지털 샘플링', 'FM 신디시스'],
    question: '악기 간 디지털 통신을 위한 국제 표준 프로토콜은?',
    questionFormat: 'multiple',
    quizType: 'knowledge',
  },
  {
    answer: '전위 음악',
    category: 'kpop-music',
    difficulty: 'hard',
    options: ['전위 음악', '고전 음악', '재즈', '트로트'],
    question: '기존 음악 관습을 거부하고 새로운 표현을 탐구한 음악은?',
    questionFormat: 'multiple',
    quizType: 'knowledge',
  },
  {
    answer: '테이프 음악',
    category: 'kpop-music',
    difficulty: 'hard',
    options: ['테이프 음악', '실시간 연주', '라이브 일렉트로닉', '미디'],
    question: '사전 녹음된 소리를 조작해 재생하는 전자 음악 방식은?',
    questionFormat: 'multiple',
    quizType: 'knowledge',
  },
  {
    answer: '존 케이지',
    category: 'kpop-music',
    difficulty: 'hard',
    options: ['존 케이지', '필립 글래스', '스티브 라이히', '테리 라일리'],
    question: '4분 33초의 무음 작품으로 유명한 실험 음악가는?',
    questionFormat: 'multiple',
    quizType: 'knowledge',
  },
  {
    answer: '확률 음악',
    category: 'kpop-music',
    difficulty: 'hard',
    options: ['확률 음악', '전자 음악', '프랙탈 음악', '클러스터 음악'],
    question: '연주 결과가 연주자의 선택이나 우연에 따라 달라지는 음악은?',
    questionFormat: 'multiple',
    quizType: 'knowledge',
  },
  {
    answer: '신시사이저',
    category: 'kpop-music',
    difficulty: 'hard',
    options: ['신시사이저', '건반', '미디 키보드', '에코 머신'],
    question: '다양한 음색을 전자적으로 생성하는 장치는?',
    questionFormat: 'multiple',
    quizType: 'knowledge',
  },
  {
    answer: '에드가 바레즈',
    category: 'kpop-music',
    difficulty: 'hard',
    options: ['에드가 바레즈', '리게티', '존 케이지', '말러'],
    question: '소리의 공간성과 과학적 접근을 중시한 20세기 작곡가는?',
    questionFormat: 'multiple',
    quizType: 'knowledge',
  },
  {
    answer: '구체 음악',
    category: 'kpop-music',
    difficulty: 'hard',
    options: ['구체 음악', '전자 음악', '미니멀 음악', '노이즈 음악'],
    question: '자연 소리나 환경음을 편집하여 만든 음악은?',
    questionFormat: 'multiple',
    quizType: 'knowledge',
  },
  {
    answer: '직관적 음악',
    category: 'kpop-music',
    difficulty: 'hard',
    options: ['직관적 음악', '즉흥 연주', '정형 음악', '기계 음악'],
    question: '형식적 악보 대신 언어나 지시문을 기반으로 연주하는 음악은?',
    questionFormat: 'multiple',
    quizType: 'knowledge',
  },
  {
    answer: '그래픽 스코어',
    category: 'kpop-music',
    difficulty: 'hard',
    options: ['그래픽 스코어', '정형 악보', '지휘 기호', '음정 스케치'],
    question: '기호, 도형 등으로 연주를 지시하는 현대 악보 방식은?',
    questionFormat: 'multiple',
    quizType: 'knowledge',
  },
  {
    answer: '전자음향 음악',
    category: 'kpop-music',
    difficulty: 'hard',
    options: ['전자음향 음악', '관현악', '솔로곡', '합창곡'],
    question: '전자 기기를 통해 만들어진 소리로 구성된 음악은?',
    questionFormat: 'multiple',
    quizType: 'knowledge',
  },
  {
    answer: '필립 글래스',
    category: 'kpop-music',
    difficulty: 'hard',
    options: ['필립 글래스', '존 케이지', '파울 힌데미트', '헨리 퍼셀'],
    question: '미니멀리즘 작곡가로 유명한 미국 음악가는?',
    questionFormat: 'multiple',
    quizType: 'knowledge',
  },
  {
    answer: '음향 설치',
    category: 'kpop-music',
    difficulty: 'hard',
    options: ['음향 설치', '소나타 형식', '연가곡', '뮤지컬'],
    question: '공간과 관람자의 경험을 고려하여 배치된 소리 예술은?',
    questionFormat: 'multiple',
    quizType: 'knowledge',
  },
  {
    answer: '잔음',
    category: 'kpop-music',
    difficulty: 'hard',
    options: ['잔음', '잔향', '지속음', '공명음'],
    question: '소리가 멈춘 뒤 남아있는 미세한 음의 흔적은?',
    questionFormat: 'multiple',
    quizType: 'knowledge',
  },
  {
    answer: '분산 화성',
    category: 'kpop-music',
    difficulty: 'hard',
    options: ['분산 화성', '단선율', '이조', '조표'],
    question: '전통 화성에서 벗어나 음들을 넓게 펼쳐 배열하는 기법은?',
    questionFormat: 'multiple',
    quizType: 'knowledge',
  },
  {
    answer: '펜타토닉 스케일',
    category: 'kpop-music',
    difficulty: 'hard',
    options: [
      '펜타토닉 스케일',
      '블루스 스케일',
      '도리아 스케일',
      '크로매틱 스케일',
    ],
    question: '5음으로 이루어진 음계로, 민속 음악에 자주 등장하는 음계는?',
    questionFormat: 'multiple',
    quizType: 'knowledge',
  },
  {
    answer: '마이크로톤',
    category: 'kpop-music',
    difficulty: 'hard',
    options: ['마이크로톤', '세미톤', '전음', '반음'],
    question: '서양 음악의 반음보다 더 작은 음 간격을 무엇이라 하는가?',
    questionFormat: 'multiple',
    quizType: 'knowledge',
  },
  {
    answer: '비트',
    category: 'kpop-music',
    difficulty: 'hard',
    options: ['비트', '하모닉스', '서스테인', '글리산도'],
    question: '주파수가 유사한 두 음이 만나 생기는 진동의 간섭 효과는?',
    questionFormat: 'multiple',
    quizType: 'knowledge',
  },
  {
    answer: '피드백',
    category: 'kpop-music',
    difficulty: 'hard',
    options: ['피드백', '컴프레서', '디스토션', '리버브'],
    question: '출력된 소리가 입력으로 다시 들어가 증폭되는 현상은?',
    questionFormat: 'multiple',
    quizType: 'knowledge',
  },
];

export const uploadQuiz = async (insertQuiz: any) => {
  for (const quiz of quizzes) {
    try {
      await insertQuiz(quiz as any);
      console.log(`✅ Uploaded: ${quiz.question}`);
    } catch (error) {
      console.error(`❌ Failed: ${quiz.question}`, error);
    }
  }
};
