import Head from 'next/head'
import Banner from '../components/Banner'
import Header from '../components/Header'
import HomeScreen from '../components/HomeScreen'
import Row from '../components/Row'
import { Movie } from '../typing'
import requests from '../utils/requests'
import { useSelector, useDispatch } from 'react-redux'
import { signin, signout } from '../slices/userSlice'
import type { RootState } from '../store'
import { auth } from '../firebase'
import { useEffect, useState } from 'react'
import { onAuthStateChanged } from 'firebase/auth'

interface Props {
  netflixOriginals: Movie[]
  trendingNow: Movie[]
  topRated: Movie[]
  actionMovies: Movie[]
  comedyMovies: Movie[]
  horrorMovies: Movie[]
  romanceMovies: Movie[]
  documentaries: Movie[]
}

const Home = ({
    netflixOriginals,
    actionMovies,
    comedyMovies,
    documentaries,
    horrorMovies,
    romanceMovies,
    topRated,
    trendingNow,
  }: Props) => 
{ 
  const [isSignedIn, setIsSignedIn] = useState(false)

  useEffect(() => {
      onAuthStateChanged(auth, user => {
        if (user) {
          setIsSignedIn(true)
        } else {
          setIsSignedIn(false)
        }
      })
    }, [])

  return (
    isSignedIn ? 
        <div>
          <Head>
            <title>Netflix South Korea - Watch TV Shows Online, Watch Movies Online</title>
            <meta name="description" content="Generated by create next app" />
          </Head>
      
          <Header />
      
          <main>
            <Banner netflixOriginals={netflixOriginals}/>
      
            <section className='absolute top-2/3 sm:top-[60%] space-y-10 pb-10 px-5 sm:px-10'>
              <Row title="Trending Now" movies={trendingNow} />
              <Row title="Top Rated" movies={topRated}/>
              <Row title="Action Movies" movies={actionMovies}/>
              <Row title="Comedy Movies" movies={comedyMovies}/>
              <Row title="Horror Movies" movies={horrorMovies}/>
              <Row title="Romance Movies" movies={romanceMovies}/>
            </section>
          </main>
        </div>
      : <HomeScreen />
  )
}

export default Home

export const getServerSideProps = async () => {
  const [
    netflixOriginals,
    trendingNow,
    topRated,
    actionMovies,
    comedyMovies,
    horrorMovies,
    romanceMovies,
    documentaries,
  ] = await Promise.all([
    fetch(requests.fetchNetflixOriginals).then(res => res.json()),
    fetch(requests.fetchTrending).then(res => res.json()),
    fetch(requests.fetchTopRated).then(res => res.json()),
    fetch(requests.fetchActionMovies).then(res => res.json()),
    fetch(requests.fetchComedyMovies).then(res => res.json()),
    fetch(requests.fetchHorrorMovies).then(res => res.json()),
    fetch(requests.fetchRomanceMovies).then(res => res.json()),
    fetch(requests.fetchDocumentaries).then(res => res.json()),
  ])

  return {
    props: {
      netflixOriginals: netflixOriginals.results,
      trendingNow: trendingNow.results,
      topRated: topRated.results,
      actionMovies: actionMovies.results,
      comedyMovies: comedyMovies.results,
      horrorMovies: horrorMovies.results,
      romanceMovies: romanceMovies.results,
      documentaries: documentaries.results,
    }
  }
}